version: "3"
services:

  # MySQL
  mysql_db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: Networkly
        MYSQL_USER: user
        MYSQL_PASSWORD: pwd12345
    volumes: 
        - ./server/src/:/docker-entrypoint-initdb.d
        - mysql_data:/var/lib/mysql
    ports: 
        - 3306:3306

  # MySQL adminer
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
        - 8543:8080


  # Redis
  redis_db:
    image: redis
    container_name: redis_db
    restart: always
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
        #- REDISCLI_AUTH=contraseña
    volumes: 
        - mysql_data:/data
    ports:
        - 6379:6379


  # Backend
  backend:
    #image: crazyhao/networkly-server
    build: 
      context : "./"
      dockerfile: "dockerfile.server"
    container_name: networkly-backend
    depends_on:
      - mysql_db
      - adminer
      - redis_db

    #enable live reload on development
    volumes:
      - ./server:/app/server:cached
    
    ports:  
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - WAIT_HOSTS=mysql_db:3306,adminer:8543,redis_db:6379
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30


  # Frontend
  frontend:
    #image: crazyhao/networkly-client
    build: 
      context : "./"
      dockerfile: "dockerfile.client"
    container_name: networkly-frontend

    #enable live reload on development    
    volumes:
      - ./client:/app/client:cached
      - /app/client/node_modules

    ports:
      - 8080:8080 
    environment: 
      - CHOKIDAR_USEPOLLING=true


volumes:
  mysql_data: