FROM python:3

#Set working directory
WORKDIR /backend

#install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

#Copy all to container
COPY ./server /backend/server
RUN ls

#setup project
WORKDIR /backend/server
ENV FLASK_APP=src

#listen on port 5000
EXPOSE 5000

#run server
CMD ["flask", "run", "--host=0.0.0.0"]