FROM node:14.17.5-alpine

# Install http server
#RUN npm install -g http-server

# hacer la carpeta 'app' el directorio de trabajo actual
WORKDIR /app

# copy 'package.json' y 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy everything to current working directory 
COPY ./client /app/client

#listen on port 8080
EXPOSE 8080

WORKDIR /app/client

# run app
CMD ["npm", "run", "serve"]