name: test-backend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r server/requirements.txt
    - name: Test with pytest
      env: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: Networkly
        MYSQL_USER: user
        MYSQL_PASSWORD: pwd12345
        MYSQL_HOST: localhost
        MYSQL_PORT: 3306
      run: |
        pip install pytest
        pip install pytest-cov
        pytest server --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
